[package]
name = "streaminterpolator"
description = "si: stream interpolator"
version = "0.1.1"
edition = "2018"
license = "MIT"

[[bin]]
name = "si"
path = "src/main.rs"
test = false
bench = false

[dependencies]
clap = "2.33.3"
serde = "1.0.128"
